version: '3'

services:
  go-monitoring:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    network_mode: host

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    network_mode: host

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    network_mode: host

  webapp1:
    build:
      context: ./webapp1
      dockerfile: Dockerfile
    container_name: webapp1
    ports:
      - "8081:8081"
    network_mode: host

  webapp2:
    build:
      context: ./webapp2
      dockerfile: Dockerfile
    container_name: webapp2
    ports:
      - "8082:8082"
    network_mode: host


